services:

  application:
    container_name: personal-site
    build:
      context: .
      dockerfile: ./Dockerfile
    image: untilov/personal-site
    restart: always
    expose:
      - 3000
    ports:
      - 3001:3000
